
const QUEUE_AUTO_RESET_DELAY_MS =
  Number(process.env.QUEUE_AUTO_RESET_DELAY_MINUTES || 15) * 60 * 1000;

const QUEUE_AUTO_RESET_CHECK_INTERVAL_MS = 60 * 1000;

export { QUEUE_AUTO_RESET_DELAY_MS, QUEUE_AUTO_RESET_CHECK_INTERVAL_MS };